<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\debile_djokes\Helper\EntityHelper;
use Drupal\debile_djokes\Helper\ViewsHelper;

/**
 * Implements hook_entity_presave().
 *
 * @see EntityHelper::presave()
 */
function debile_djokes_entity_presave(EntityInterface $entity) {
  Drupal::service(EntityHelper::class)->presave($entity);
}

/**
 * Implements hook_views_data().
 */
function debile_djokes_views_data() {
  return Drupal::service(ViewsHelper::class)->data();
}
